feat: new python workflow, new golang test suite and improvements
konstellation-io/kai-server-training pull request #6
Opened 2022-07-20 13:53 UTC by alexrodfe

## Why
We wanted to have an additional workflow containing a python node to add more examples to our training repo. We also wanted to be able to send multiple requests from our training examples to aid our testing.

## What
- New python node 'echo'
- New python workflow
- New golang test suite
- Improvements

2022-07-21 07:54 UTC, aacecandev commented
I'd really love to have functions commented since this is a training repository

2022-07-22 13:42 UTC, alexrodfe commented
Good idea @aacecandev ! I have added documentation regarding full disclosure of the whole repo. Hope it is useful.

2022-07-22 15:03 UTC, JYisus requested changes

2022-07-22 15:03 UTC, JYisus commented on descriptor/src/etl/main.go
>  	"github.com/golang/protobuf/proto"
@alexrodfe maybe we can use `protobuf` as alias for this package

2022-07-22 15:03 UTC, JYisus commented on test_go/main.go
> +// the goal of this go executable is to emulate several clients making requests at the same time
@alexrodfe In my opinion, this description should be in the README of the repo.

2022-07-22 15:12 UTC, JYisus commented
> I'd really love to have functions commented since this is a training repository

@aacecandev @alexrodfe The main functions are documented in the wiki, maybe we should link the wiki in the README, but having the code overcommented is a bad practice. The code must be enough clear to explain itself, and comments make the code hard to maintain (because you have to maintain the code and the comments). I'd keep comments of the helpers functions that have some complexity, but the handler, handlerInit and all the context functions are already explained in the wiki.

2022-07-26 10:37 UTC, alexrodfe commented on descriptor/krt.yml
> +  image: konstellation/kre-entrypoint:1.8.0
Oh, alright seems fine by me :+1:

2022-07-26 10:38 UTC, alexrodfe commented on descriptor/src/etl/main.go
> +	localProto "main/proto"
I don't think its relevant to where the proto is generated, we are still using several packages being named/related to proto at the same time.
Maybe having the protobuf/proto package renamed to protobuf and the local proto to proto is clearer.

2022-07-26 10:40 UTC, alexrodfe commented on descriptor/src/etl/main.go
>  	err := anypb.UnmarshalTo(data, req, proto2.UnmarshalOptions{})
proto2 for this main.go is the "google.golang.org/protobuf/proto" package

2022-07-26 13:57 UTC, alexrodfe commented on test_go/main.go
> +// the goal of this go executable is to emulate several clients making requests at the same time
Seems like a good idea, I have updated the readme.

2022-07-26 13:58 UTC, alexrodfe commented
Agreed with @JYisus resolution. I have deleted comments explained in the docs and maintained comments for those auxiliary funcitons.

2022-07-26 13:59 UTC, alexrodfe commented on descriptor/src/etl/main.go
>  	"github.com/golang/protobuf/proto"
With the new refactor of the golang runner I have set new aliases. As we now only have 2 proto packages the one coming from google will be named alias 'protobuf' and our local generated proto will stay as alias 'proto'.

2022-07-26 14:30 UTC, alexrodfe commented
I am aware I left replace instructions in the go.mod files. I will delete those once we have merged our new kre-go runners updated with the new proto packages.

2022-07-27 07:53 UTC, JYisus commented
> I am aware I left replace instructions in the go.mod files. I will delete those once we have merged our new kre-go runners updated with the new proto packages.

Okay, but you have to delete this lines before merge

2022-07-27 07:54 UTC, JYisus approved these changes

2022-07-27 07:55 UTC, JYisus requested changes

2022-07-27 07:55 UTC, JYisus commented on README.md
>  ./scripts/run_test.sh kre descriptor-v1 GoDescriptor 2 Alex
@alexrodfe  i would put as an example a real repo instead of Alex

2022-07-28 06:28 UTC, aacecandev commented on descriptor/krt.yml
> +  image: konstellation/kre-entrypoint:1.8.0
I totally disagree with this @JYisus. From almost every POV, using latest is a bad practice.

2022-07-29 06:53 UTC, aacecandev approved these changes
Good work guys, I like the PR. Comments are very helpful to those new to Go and KRE like me

2022-07-29 09:53 UTC, JYisus approved these changes

2022-07-29 09:55 UTC, merged